[general]
import = ["~/.config/alacritty/alacritty-theme/themes/dracula.toml"]
live_config_reload = true

[bell]
animation = "EaseOutExpo"
duration = 5

[font]
normal = {family = "Cozette"}

[mouse]
hide_when_typing = true

[colors]
transparent_background_colors = false

[window]
opacity = 0.7
